FROM registry.redhat.io/rhel9/rhel-bootc:9.6


################################################################################
#Red Hat Edge Manager
################################################################################
RUN dnf -y copr enable @redhat-et/flightctl && \
    dnf -y install flightctl-agent && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer

# Optional: To enable podman-compose application support, uncomment below
 RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
     dnf -y install podman-compose && \
     dnf -y clean all && \
     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
     systemctl enable podman.service

################################################################################
# Customization
################################################################################

RUN useradd -m -d /var/home/kiosk kiosk 

RUN dnf install -y shadow-utils gnome-kiosk gdm gnome-kiosk-script-session  git firefox \
    && dnf clean all

RUN mkdir -p /var/home/kiosk/.local/bin/ /etc/accountsservice/user-templates /etc/gdm/

COPY files/ /

RUN chmod +x /var/home/kiosk/.local/bin/gnome-kiosk-script && \
    chown -R kiosk:kiosk /var/home/kiosk

RUN systemctl set-default graphical.target

#////////////////////////////////////////
#DEMO V2 update (cockpit + kvm + firewall)
#////////////////////////////////////////
#RUN dnf install -y cockpit cockpit-machines cockpit-podman cockpit-system cockpit-bridge cockpit-pcp cockpit-storaged cockpit-session-recording cockpit-navigator && \
#    systemctl enable cockpit.socket && \
#    firewall-offline-cmd --zone=public --add-port=9090/tcp && \
#    dnf clean all

## Build and install the SELinux module for Cockpit
#RUN checkmodule -M -m -o /tmp/my-cockpit.mod /tmp/my-cockpit.te && \
#    semodule_package -o /tmp/my-cockpit.pp -m /tmp/my-cockpit.mod && \
#    semodule -X 300 -i /tmp/my-cockpit.pp && \
#    restorecon -Rv /usr 

#////////////////////////////////////////

