#!/bin/sh
set -Eeuo pipefail
export MOZ_ENABLE_WAYLAND=1
while ! curl -sf --connect-timeout 5 --expect100-timeout 5 https://demo.home-assistant.io; do
    echo "Waiting for the Kiosk APP to become available..."
    sleep 10
done
exec /usr/bin/firefox --kiosk https://demo.home-assistant.io