ARG BASE_IMAGE_TAG='9.6'

########################################
FROM registry.redhat.io/rhel9/rhel-bootc:${BASE_IMAGE_TAG}

################################################################################
#Red Hat Edge Manager
################################################################################

RUN dnf config-manager \
        --set-enabled edge-manager-1.0-for-rhel-9-$(uname -m)-rpms && \
    dnf -y install flightctl-agent flightctl-cli && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer 

# Optional: To enable podman-compose application support, uncomment below
 RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
     dnf -y install podman-compose && \
     dnf -y clean all && \
     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
     systemctl enable podman.service

################################################################################
# Customization
################################################################################


RUN dnf install -y stress xz yq podman-plugins inotify-tools firewalld dialog && \
    dnf clean all

COPY files/ /

RUN chmod +x /usr/local/bin/* && \
    ln -s /usr/lib/systemd/system/first-boot.service /etc/systemd/system/multi-user.target.wants/first-boot.service && \
    ln -s /usr/lib/systemd/system/hook-files.service /etc/systemd/system/multi-user.target.wants/hook-files.service



################################################################################
# v2 (splitted here for demo)
################################################################################

RUN dnf install -y cockpit cockpit-podman cockpit-system cockpit-bridge cockpit-pcp cockpit-storaged cockpit-session-recording cockpit-navigator && \
    systemctl enable cockpit.socket && \
    firewall-offline-cmd --zone=public --add-port=9090/tcp && \
    dnf clean all

