---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
    argocd.argoproj.io/sync-wave: "14"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: app-store-global
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: app-stores-helm-hello
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: Application
                metadata:
                  name: '{{hub .ManagedClusterName hub}}-helm-hello'
                  namespace: openshift-gitops
                  labels:
                    app.kubernetes.io/managed-by: stores-apps-helm-global
                spec:
                  destination:
                    namespace: hello
                    server: https://kubernetes.default.svc
                  project: stores
                  source:
                    path: apps/k8s/helm/hello
                    repoURL: https://github.com/luisarizmendi/rhem-demo.git
                    targetRevision: main
                    helm:
                      valueFiles:
                        - values.yaml
                        - 'environment/function/values-{{hub (index .ManagedClusterLabels "function") hub}}.yaml'
                        - 'environment/site/values-{{hub (index .ManagedClusterLabels "site") hub}}.yaml'
                  syncPolicy:
                    automated:
                      selfHeal: true
                      prune: true
                    syncOptions:
                      - CreateNamespace=true
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
    argocd.argoproj.io/sync-wave: "14"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: app-store-pos
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: app-store-pos
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: argoproj.io/v1alpha1
            kind: AppProject
            metadata:
              name: stores
              namespace: openshift-gitops
            spec:
              clusterResourceWhitelist:
              - group: '*'
                kind: '*'
              description: Project for store APPs
              destinations:
              - namespace: '*'
                server: https://kubernetes.default.svc
              sourceRepos:
              - '*'
        - complianceType: musthave
          objectDefinition:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: tailwind-pos
              namespace: openshift-gitops
            spec:
              destination:
                namespace: pos
                server: https://kubernetes.default.svc
              ignoreDifferences:
              - group: argoproj.io
                jsonPointers:
                - /spec/syncPolicy/automated
                kind: Application
                managedFieldsManagers:
                - argocd-server
              project: stores
              source:
                path: apps/k8s/manifests/tailwind-pos/deploy
                repoURL: https://github.com/luisarizmendi/rhem-demo.git
                targetRevision: main
              syncPolicy:
                automated:
                  prune: true
                  selfHeal: true
                syncOptions:
                  - CreateNamespace=true
        remediationAction: enforce
        severity: low
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
    argocd.argoproj.io/sync-wave: "14"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: app-store-infra
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: app-store-infra
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: argoproj.io/v1alpha1
            kind: AppProject
            metadata:
              name: stores
              namespace: openshift-gitops
            spec:
              clusterResourceWhitelist:
              - group: '*'
                kind: '*'
              description: Project for store APPs
              destinations:
              - namespace: '*'
                server: https://kubernetes.default.svc
              sourceRepos:
              - '*'
        - complianceType: musthave
          objectDefinition:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: http-server-upload
              namespace: openshift-gitops
            spec:
              destination:
                namespace: infra
                server: https://kubernetes.default.svc
              ignoreDifferences:
              - group: argoproj.io
                jsonPointers:
                - /spec/syncPolicy/automated
                kind: Application
                managedFieldsManagers:
                - argocd-server
              project: stores
              source:
                path: apps/k8s/manifests/http-server-upload/deploy
                repoURL: https://github.com/luisarizmendi/rhem-demo.git
                targetRevision: main
              syncPolicy:
                automated:
                  selfHeal: true
                  prune: true
                syncOptions:
                  - CreateNamespace=true
        remediationAction: enforce
        severity: low
  remediationAction: enforce