apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: microshift-gitops-policy-generator
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
placementBindingDefaults:
  name: "binding-policy-gitops"
policies:
  - name: microshift-bootstrap-app
    remediationAction: enforce
    manifests:
      - path: manifests/bootstrap-app
policySets:
  - name: "microshift-gitops"
    description: "Policy for bootstrapping Microshift with GitOps"
    policies:
      - microshift-bootstrap-app
    placement:
      name: placement-microshift-gitops
