---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: stores
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "13"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterSets:
    - stores
#  numberOfClusters: 1
#  predicates:
#    - requiredClusterSelector:
#        claimSelector:
#          matchExpressions:
#            - key: device.status
#              operator: NotIn
#              values:
#                - disabled
#  prioritizerPolicy:
#    configurations:
#      - scoreCoordinate:
#          builtIn: ResourceAllocatableCPU
#        weight: 2
#      - scoreCoordinate:
#          builtIn: ResourceAllocatableMemory
#        weight: 2

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: stores-pos
  namespace: openshift-gitops
spec:
  clusterSets:
    - stores
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            function: pos
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: stores-infra
  namespace: openshift-gitops
spec:
  clusterSets:
    - stores
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            function: infra