apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/managed-by: stores-apps-helm-global
  name: stores-apps-helm-global
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - git:
              directories:
                - path: apps/k8s/helm/*
              repoURL: 'https://github.com/luisarizmendi/rhem-demo.git'
              revision: main
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: stores
              requeueAfterSeconds: 180
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: stores-apps-helm-global
      name: '{{.name}}-{{.path.basename}}'
    spec:
      destination:
        namespace: '{{.path.basename}}'
        server: '{{.server}}'
      project: stores
      source:
        helm:
          valueFiles:
            - values.yaml
            - 'environment/function/values-{{.function}}.yaml'
            - 'environment/site/values-{{.site}}.yaml'
        path: '{{.path.path}}'
        repoURL: 'https://github.com/luisarizmendi/rhem-demo.git'
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stores-app-pos
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: stores
        requeueAfterSeconds: 180
  goTemplate: true
  template:
    metadata:
      name: '{{.name}}-pos'
      labels:
        app: pos
        clusterset: store-pos
    spec:
      destination:
        namespace: pos
        server: '{{.server}}'
      project: stores
      source:
        path: apps/k8s/manifests/tailwind-pos
        repoURL: 'https://github.com/luisarizmendi/rhem-demo.git'
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stores-app-infra
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: stores
        requeueAfterSeconds: 180
  goTemplate: true
  template:
    metadata:
      name: '{{.name}}-infra'
      labels:
        app: infra
        clusterset: store-infra
    spec:
      destination:
        namespace: infra
        server: '{{.server}}'
      project: stores
      source:
        path: apps/k8s/manifests/http-server-upload
        repoURL: 'https://github.com/luisarizmendi/rhem-demo.git'
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true