#!/bin/sh
set -Eeuo pipefail
export MOZ_ENABLE_WAYLAND=1
while ! curl -sf --connect-timeout 5 --expect100-timeout 5 https://play.grafana.org/d/timeline-demo/timeline-demo?kiosk&orgId=1&from=now-1h&to=now&timezone=utc&refresh=auto; do
    echo "Waiting for the Kiosk APP to become available..."
    sleep 10
done
exec /usr/bin/firefox --kiosk https://play.grafana.org/d/timeline-demo/timeline-demo?kiosk&orgId=1&from=now-1h&to=now&timezone=utc&refresh=auto