---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: stores
  namespace: store-clusters
  annotations:
    argocd.argoproj.io/sync-wave: "13"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterSets:
    - store-pos
    - store-infra
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        claimSelector:
          matchExpressions:
            - key: device.status
              operator: NotIn
              values:
                - disabled
#  prioritizerPolicy:
#    configurations:
#      - scoreCoordinate:
#          builtIn: ResourceAllocatableCPU
#        weight: 2
#      - scoreCoordinate:
#          builtIn: ResourceAllocatableMemory
#        weight: 2