ARG BASE_IMAGE_TAG='9.6'
ARG USHIFT_VER='4.20'
ARG ACM_VER='2.14'
########################################
FROM registry.redhat.io/rhel9/rhel-bootc:${BASE_IMAGE_TAG}

ARG ACM_VER
ARG USHIFT_VER

################################################################################
#Red Hat Edge Manager
################################################################################

RUN dnf config-manager \
        --set-enabled rhacm-${ACM_VER}-for-rhel-9-$(uname -m)-rpms && \
    dnf -y install flightctl-agent flightctl && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer 

# Optional: To enable podman-compose application support, uncomment below
 RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
     dnf -y install podman-compose && \
     dnf -y clean all && \
     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
     systemctl enable podman.service

################################################################################

RUN dnf config-manager \
        --set-enabled rhocp-${USHIFT_VER}-for-rhel-9-$(uname -m)-rpms \
        --set-enabled fast-datapath-for-rhel-9-$(uname -m)-rpms \
        --set-enabled gitops-1.16-for-rhel-9-$(uname -m)-rpms


RUN dnf install -y xz yq podman-plugins inotify-tools firewalld microshift microshift-cert-manager microshift-olm microshift-gitops dialog certmonger ipa-client  \
     cockpit cockpit-machines cockpit-podman cockpit-system cockpit-bridge cockpit-pcp cockpit-storaged cockpit-session-recording cockpit-navigator && \
    systemctl enable microshift && \
    systemctl enable cockpit.socket && \
    dnf clean all

COPY files/ /

RUN chmod +x /usr/local/bin/* && \
    ln -s /usr/lib/systemd/system/first-boot.service /etc/systemd/system/multi-user.target.wants/first-boot.service && \
    ln -s /usr/lib/systemd/system/hook-files.service /etc/systemd/system/multi-user.target.wants/hook-files.service


RUN firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16 && \
    firewall-offline-cmd --zone=trusted --add-source=169.254.169.1 && \
    firewall-offline-cmd --zone=public --add-port=22/tcp && \
    firewall-offline-cmd --zone=public --add-port=80/tcp && \
    firewall-offline-cmd --zone=public --add-port=443/tcp && \
    firewall-offline-cmd --zone=public --add-port=6443/tcp && \
    firewall-offline-cmd --zone=public --add-port=30000-32767/tcp

# Certmonger restart
RUN mkdir -p /etc/systemd/system/certmonger.service.d && \
    echo -e "[Service]\nRestart=on-failure\nRestartSec=10s" > /etc/systemd/system/certmonger.service.d/restart.conf

# Generate new initramfs.img with systemd-cryptenroll support
RUN set -xe; \
    kver=$(ls /usr/lib/modules | sort -Vr | head -n1); \
    dracut --force --add "crypt systemd tpm2-tss" \
           --install "systemd-cryptenroll cryptsetup" \
           --no-hostonly \
           /usr/lib/modules/$kver/initramfs.img "$kver"
