apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels: {}
  name: kiosk
spec:
  selector:
    matchLabels:
      fleet: "kiosk"
  template:
    metadata:
      labels:
        fleet: kiosk
    spec:
      applications:
      - appType: compose
        envVars:
          PGADMIN_MAIL: pgadmin@none.com
          PGADMIN_PW: pgredhat
          POSTGRES_DB: postgres
          POSTGRES_PW: pgadmin
          POSTGRES_USER: pgredhat
        image: ghcr.io/luisarizmendi/app-postgres:v1
        name: postgres
      config:
      - name: motd-update
        configType: InlineConfigProviderSpec
        inline:
          - path: "/etc/motd"
            content: "This system is managed by flightctl."
            mode: 0644
      - gitRef:
          mountPath: /
          path: /configs/kiosk/site/{{ .metadata.labels.site }}
          repository: rhem-demo
          targetRevision: main
        name: site-conf
      - gitRef:
          mountPath: /
          path: /configs/kiosk/function/{{ .metadata.labels.function }}
          repository: rhem-demo
          targetRevision: main
        name: function-conf
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
      os:
        image: ghcr.io/luisarizmendi/device-kiosk:latest-amd64



