apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels:
    environment: demo
  name: kiosk
spec:
  selector:
    matchLabels:
      fleet: "kiosk"
  template:
    metadata:
      labels:
        fleet: kiosk
    spec:
      applications:
      - name: pos
        image: ghcr.io/luisarizmendi/app-pos:v1
        ports:
          - '8080:8080'
        appType: container
        catalogItemRef:
          item: pos-container
          catalog: demo
          channel: test
          version: 1.0.0
      - appType: compose
        envVars:
          PGADMIN_MAIL: pgadmin@none.com
          PGADMIN_PW: pgredhat
          POSTGRES_DB: postgres
          POSTGRES_PW: pgadmin
          POSTGRES_USER: pgredhat
        image: ghcr.io/luisarizmendi/app-bundle-postgres-compose:v1
        name: postgres
        catalogItemRef:
          item: postgresql-compose
          catalog: demo
          channel: test
          version: 1.0.0
      config:
      - name: motd-update
        configType: InlineConfigProviderSpec
        inline:
          - path: "/etc/motd"
            content: "This system is managed by flightctl."
            mode: 0644
      - gitRef:
          mountPath: /
          path: /configs/kiosk/site/{{ .metadata.labels.site }}
          repository: rhem-demo
          targetRevision: main
        name: site-conf
      - gitRef:
          mountPath: /
          path: /configs/kiosk/function/{{ .metadata.labels.function }}
          repository: rhem-demo
          targetRevision: main
        name: function-conf
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
      os:
        image: ghcr.io/luisarizmendi/device-kiosk:v1
        catalogItemRef:
          item: rhel-kiosk-os
          catalog: demo
          channel: test
          version: 1.0.0


