apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels:
    os.catalog.flightctl.io/catalog: demo
    os.catalog.flightctl.io/channel: test
    os.catalog.flightctl.io/item: rhel-kiosk-os
    pos.app.catalog.flightctl.io/catalog: demo
    pos.app.catalog.flightctl.io/channel: test
    pos.app.catalog.flightctl.io/item: pos-container
    postgres.app.catalog.flightctl.io/catalog: demo
    postgres.app.catalog.flightctl.io/channel: test
    postgres.app.catalog.flightctl.io/item: postgresql-compose
  name: kiosk
spec:
  selector:
    matchLabels:
      fleet: "kiosk"
  template:
    metadata:
      labels:
        fleet: kiosk
    spec:
      applications:
      - appType: container
        envVars: {}
        image: quay.io/luisarizmendi/2048:v3
        name: '2048'
        ports:
          - '8081:8081'
        volumes: []
      - appType: compose
        envVars:
          PGADMIN_MAIL: pgadmin@none.com
          PGADMIN_PW: pgredhat
          POSTGRES_DB: postgres
          POSTGRES_PW: pgadmin
          POSTGRES_USER: pgredhat
        image: ghcr.io/luisarizmendi/app-bundle-postgres-compose:v1
        name: postgres
      config:
      - name: motd-update
        configType: InlineConfigProviderSpec
        inline:
          - path: "/etc/motd"
            content: "This system is managed by flightctl."
            mode: 0644
      - gitRef:
          mountPath: /
          path: /configs/kiosk/site/{{ .metadata.labels.site }}
          repository: rhem-demo
          targetRevision: main
        name: site-conf
      - gitRef:
          mountPath: /
          path: /configs/kiosk/function/{{ .metadata.labels.function }}
          repository: rhem-demo
          targetRevision: main
        name: function-conf
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
      os:
        image: ghcr.io/luisarizmendi/device-kiosk:v1-amd64



