apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels: 
    postgres.app.catalog.flightctl.io/catalog: demo
    postgres.app.catalog.flightctl.io/channel: test
    postgres.app.catalog.flightctl.io/item: postgresql-quadlet
  name: kvm
spec:
  selector:
    matchLabels:
      fleet: "kvm"
  template:
    metadata:
      labels:
        fleet: kvm
    spec:
      applications:
      - appType: quadlet
        envVars:
          PGADMIN_MAIL: pgadmin@none.com
          PGADMIN_PW: pgredhat
          POSTGRES_DB: postgres
          POSTGRES_PW: pgadmin
          POSTGRES_USER: pgredhat
        image: ghcr.io/luisarizmendi/app-bundle-postgres-quadlet:v1
        name: postgres
        volumes: []
      config:
      - name: motd-update
        configType: InlineConfigProviderSpec
        inline:
          - path: "/etc/motd"
            content: "This system is managed by flightctl."
            mode: 0644
      - gitRef:
          mountPath: /
          path: /configs/kvm
          repository: rhem-demo
          targetRevision: main
        name: vms
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
          - "libvirt-vm*.service"
      os:
        image: ghcr.io/luisarizmendi/device-rhel-kvm:latest-amd64



