apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels:
    environment: demo
  name: kvm
spec:
  selector:
    matchLabels:
      fleet: "kvm"
  template:
    metadata:
      labels:
        fleet: kvm
    spec:
      applications:
      - name: postgresql-quadlet
        runAs: root
        appType: quadlet
        volumes: []
        PGADMIN_PW: pgredhat
        POSTGRES_PW: pgredhat
        catalogItemRef:
          item: postgresql-quadlet
          catalog: demo
          channel: test
          version: 1.0.0
      config:
      - name: motd-update
        configType: InlineConfigProviderSpec
        inline:
          - path: "/etc/motd"
            content: "This system is managed by flightctl."
            mode: 0644
      - gitRef:
          mountPath: /
          path: /configs/kvm
          repository: rhem-demo
          targetRevision: main
        name: vms
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
          - "libvirt-vm*.service"
      os:
        catalogItemRef:
          item: rhel-kvm-os
          catalog: demo
          channel: test
          version: 1.0.0



