apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels:
    hello.app.catalog.flightctl.io/catalog: default
    hello.app.catalog.flightctl.io/channel: test
    hello.app.catalog.flightctl.io/item: hello-world-helm
    os.catalog.flightctl.io/catalog: demo
    os.catalog.flightctl.io/channel: test
    os.catalog.flightctl.io/item: rhel-microshift-os
  name: microshift-acm
spec:
  selector:
    matchLabels:
      fleet: "microshift-acm"
  template:
    metadata:
      labels:
        fleet: microshift-acm
    spec:
      applications:
        - name: hello
          image: ghcr.io/luisarizmendi/app-bundle-hello-helm:v1
          appType: helm
      config:
      - name: acm-crd
        httpRef:
          filePath: /var/local/acm-import/crd.yaml
          repository: acm-registration
          suffix: /agent-registration/crds/v1
      - name: acm-import
        httpRef:
          filePath: /var/local/acm-import/import.yaml
          repository: acm-registration
          suffix: /agent-registration/manifests/{{.metadata.name}}
#      - name: pull-secret
#        inline:
#        - path: "/etc/crio/openshift-pull-secret"
#          content: "{\"auths\":{...}}"
      - name: site-conf
        gitRef:
          mountPath: /
          path: /configs/microshift/site/{{ .metadata.labels.site }}
          repository: rhem-demo
          targetRevision: main
      - name: apply-acm-manifests
        inline:
        - path: "/etc/flightctl/hooks.d/afterupdating/50-acm-registration.yaml"
          content: |
            - if:
              - path: /var/local/acm-import/crd.yaml
                op: [created]
              run: kubectl apply -f /var/local/acm-import/crd.yaml
              envVars:
                KUBECONFIG: /var/lib/microshift/resources/kubeadmin/kubeconfig
            - if:
              - path: /var/local/acm-import/import.yaml
                op: [created]
              run: kubectl apply -f /var/local/acm-import/import.yaml
              envVars:
                KUBECONFIG: /var/lib/microshift/resources/kubeadmin/kubeconfig
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
          - "microshift.service"
      os:
        image: ghcr.io/luisarizmendi/device-microshift:v1



