apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels: {}
  name: microshift-no-acm
spec:
  selector:
    matchLabels:
      fleet: "microshift-no-acm"
  template:
    metadata:
      labels:
        fleet: microshift-no-acm
    spec:
      config:
#      - name: pull-secret
#        inline:
#        - path: "/etc/crio/openshift-pull-secret"
#          content: "{\"auths\":{...}}"
      - name: site-conf
        gitRef:
          mountPath: /
          path: /configs/microshift/site/{{ .metadata.labels.site }}
          repository: rhem-demo
          targetRevision: main
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
          - "microshift.service"
      os:
        image: ghcr.io/luisarizmendi/device-microshift-upgrade:v1



