apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels: {}
  name: simple
spec:
  selector:
    matchLabels:
      fleet: "simple"
  template:
    metadata:
      labels:
        fleet: simple
    spec:
      os:
        image: ghcr.io/luisarizmendi/device-microshift-upgrade:v1


