services:
  postgres:
    image: docker.io/postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
#////////////////////////////////////////
#DEMO V2 update (new image version) -> comment out version 9.5
#    image: docker.io/dpage/pgadmin4:9.5
    image: docker.io/dpage/pgadmin4:9.6
#////////////////////////////////////////


    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"

    restart: always