apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels: {}
  name: demo
spec:
  selector:
    matchLabels:
      fleet: "demo"
  template:
    metadata:
      labels:
        fleet: demo
    spec:
      applications:
      - envVars:
          PGADMIN_MAIL: pgadmin@none.com
          PGADMIN_PW: pgredhat
          POSTGRES_DB: postgres
          POSTGRES_PW: pgadmin
          POSTGRES_USER: pgredhat
        image: ghcr.io/luisarizmendi/app-demo-postgres:v1
        name: postgres
      config:
      - name: motd-update
        configType: InlineConfigProviderSpec
        inline:
          - path: "/etc/motd"
            content: "This system is managed by flightctl."
            mode: 0644
      - gitRef:
          mountPath: /
          path: /configs/site/{{ .metadata.labels.site }}
          repository: rhem-demo
          targetRevision: main
        name: site-config
      - gitRef:
          mountPath: /
          path: /configs/function/{{ .metadata.labels.function }}
          repository: rhem-demo
          targetRevision: main
        name: function-config
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
      os:
        image: ghcr.io/luisarizmendi/device-demo-kiosk:v4



