FROM quay.io/redhat-user-workloads/jetpack-for-rhel-tenant/rhel-102-bootc:7.2.1_6.12.0-211.61.1_093026125848

ARG BASE_IMAGE_RELEASE='10'
ARG RHEM_RELEASE='1.3'
#
################################################################################
#Red Hat Edge Manager
################################################################################

RUN dnf config-manager \
        --set-enabled edge-manager-${RHEM_RELEASE}-for-rhel-${BASE_IMAGE_RELEASE}-$(uname -m)-rpms && \
    dnf -y install flightctl-agent flightctl-cli && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer 

## Optional: To enable podman-compose application support, uncomment below
RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-${BASE_IMAGE_RELEASE}.noarch.rpm && \
    dnf -y install podman-compose && \
    dnf -y clean all && \
    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
    systemctl enable podman.service

##########
# Additional packages
RUN dnf -y install \
            tmux \
            python3-pip \
            git && \
    dnf -y clean all

### Copy files
COPY files/ /

RUN chmod -R 600 /etc/NetworkManager/system-connections/ && \
    chmod +x /usr/local/bin/set-hostname-from-mac.sh && \
    systemctl enable mac-hostname.service

################################################################################
######################    USER FOR ROOTLESS CONTAINERS  ########################
################################################################################

# Create user and groups for the rootless containers
RUN useradd -M -d /var/home/detector detector && \
#    grep video /usr/lib/group | tee -a /etc/group && \
    usermod -aG video detector

# Create the GPU group to access the GPU
RUN groupadd -r -g 1980 gpu && \
    usermod -aG gpu detector && \
    systemctl enable tegra-dev-perms.service


# Export the XDG_RUNTIME_DIR by default (so systemctl --user cli works)
RUN cat > /etc/profile.d/xdg-runtime-dir.sh << 'EOF'
export XDG_RUNTIME_DIR=/run/user/$(id -u)
EOF


# Required for /run/user/1000 — use UID, not username
RUN systemctl enable user-runtime-dir@1000.service && \
    systemctl enable user@1000.service


################################################################################
######################    EMBED IMAGES   #######################################
################################################################################

############ Script permissions and systemd enable ############
RUN chmod 755 /usr/local/bin/embed_image.sh && \
    chmod 755 /usr/local/bin/copy_embedded_images.sh && \
    systemctl enable copy-embedded-images.service

############ Images to embed ############
#RUN /usr/local/bin/embed_image.sh quay.io/luisarizmendi/object-detection-custom-camera-capture:latest --user detector
#RUN /usr/local/bin/embed_image.sh quay.io/luisarizmendi/object-detection-custom-inference-tensorrt-jetson:latest --user detector
#RUN /usr/local/bin/embed_image.sh quay.io/luisarizmendi/object-detection-custom-stream-viewer:latest --user detector
