---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: stores-pull
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "13"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterSets:
    - stores-pull
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: stores-pos-pull
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "13"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterSets:
    - stores-pull
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            function: pos
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: stores-infra-pull
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "13"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterSets:
    - stores-pull
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            function: infra