FROM registry.redhat.io/rhel9/rhel-bootc:9.6

################################################################################
########## REMOVE IF YOU USE A SUBSCRIBED HOST FOR BUILDING THE IMAGE ##########
# Subscribe
################################################################################
RUN --mount=type=secret,id=username \
    --mount=type=secret,id=password \
    echo "Registering with Red Hat subscription manager..." && \
    rm -rf /etc/rhsm-host && subscription-manager register \
      --username "$(cat /run/secrets/username)" \
      --password "$(cat /run/secrets/password)" | tee /tmp/register_output && \
    grep -o 'ID: [a-f0-9-]*' /tmp/register_output | cut -d' ' -f2 > /etc/rhsm/system_id && \
    grep -o 'system name is: [a-f0-9-]*' /tmp/register_output | cut -d' ' -f4 > /etc/rhsm/host_id && \
    rm -f /tmp/register_output
################################################################################


################################################################################
#Red Hat Edge Manager
################################################################################
RUN dnf -y copr enable @redhat-et/flightctl && \
    dnf -y install flightctl-agent && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer

# Optional: To enable podman-compose application support, uncomment below
 RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
     dnf -y install podman-compose && \
     dnf -y clean all && \
     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
     systemctl enable podman.service

ADD config.yaml /etc/flightctl/


################################################################################
# Customization
################################################################################

RUN dnf install -y shadow-utils libvirt-daemon-config-network libvirt-daemon-kvm qemu-kvm qemu-img libvirt virt-install virt-viewer libguestfs-tools python3-libguestfs virt-top  \
    && dnf clean all

RUN for drv in qemu network nodedev nwfilter secret storage interface; do systemctl start virt${drv}d{,-ro,-admin}.socket; done


#////////////////////////////////////////
#DEMO V2 update (cockpit )
#////////////////////////////////////////
#RUN dnf install -y  cockpit cockpit-machines cockpit-podman cockpit-system cockpit-bridge cockpit-pcp cockpit-storaged cockpit-session-recording \
#    && dnf clean all
#
#RUN systemctl enable cockpit.socket
#////////////////////////////////////////



################################################################################
########## REMOVE IF YOU USE A SUBSCRIBED HOST FOR BUILDING THE IMAGE ##########
# Clean-up and unregistering
RUN --mount=type=secret,id=username \
    --mount=type=secret,id=password \
    echo "Unregistering…" && \
    for uuid in $(curl -s -u "$(cat /run/secrets/username):$(cat /run/secrets/password)" \
        https://cloud.redhat.com/api/inventory/v1/hosts?fqdn=$(cat /etc/rhsm/host_id) | \
        grep -o '"id":"[^"]*' | grep -o '[^"]*$'); do \
      curl -u "$(cat /run/secrets/username):$(cat /run/secrets/password)" \
        -X DELETE https://cloud.redhat.com/api/inventory/v1/hosts/$uuid -H "accept: */*"; \
    done && subscription-manager unregister && subscription-manager clean && \
    ln -s /run/secrets/rhsm /etc/rhsm-host 
################################################################################